### ISSUE TITLE
beam_search_decoder  alignment_history failed

### ISSUE THREAD

**Issue by zh794390558** [zh794390558/tensor2tensor#4]
model init
mode infer
probelm_idx 0
data_parallelism 1 ['gpu:0']
ps_devices ['gpu:0']
decode hparams [('alpha', 0.6), ('batch_size', 1), ('beam_size', 2), ('delimiter', '\n'), ('extra_length', 50), ('identity_output', False), ('max_input_size', -1), ('num_samples', 1), ('problem_idx', 0), ('return_beams', False), ('save_images', True)]

blstm (?,)
blstm (?, ?, ?, ?)
blstm (?, ?)
vocab size 258
input (?, ?, ?)
input (?, ?, ?, 512)
input (?, ?, 512)
Traceback (most recent call last):
  File "./t2t-decoder", line 104, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./t2t-decoder", line 100, in main
    dataset_split="test" if FLAGS.eval_use_test_set else None)
  File "/lustre/atlas/zhanghui/tensor2tensor/tensor2tensor/utils/decoding.py", line 155, in decode_from_dataset
    for num_predictions, prediction in enumerate(predictions):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 411, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/lustre/atlas/zhanghui/tensor2tensor/tensor2tensor/utils/model_builder.py", line 338, in wrapping_model_fn
    return model_fn(model, features, mode, hparams, **kwargs)
  File "/lustre/atlas/zhanghui/tensor2tensor/tensor2tensor/utils/model_builder.py", line 163, in model_fn
    max_idx=len(hparams.problems) - 1)
  File "/lustre/atlas/zhanghui/tensor2tensor/tensor2tensor/utils/input_fn_builder.py", line 182, in cond_on_index
    return fn(cur_idx)
  File "/lustre/atlas/zhanghui/tensor2tensor/tensor2tensor/utils/model_builder.py", line 119, in nth_model
    decode_length=decode_hp.extra_length)
  File "/lustre/atlas/zhanghui/tensor2tensor/tensor2tensor/models/blstm.py", line 383, in infer
    features["targets"], self._hparams, self._problem_hparams, self._decode_hparams)
  File "/lustre/atlas/zhanghui/tensor2tensor/tensor2tensor/models/blstm.py", line 337, in blstm_seq2seq_internal_attention
    final_encoder_state, encoder_outputs)
  File "/lustre/atlas/zhanghui/tensor2tensor/tensor2tensor/models/blstm.py", line 286, in lstm_attention_decoder_infer
    output_layer=tf.layers.Dense(vocab_size, use_bias=False),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 226, in __init__
    initial_state, self._cell.state_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/nest.py", line 407, in map_structure
    assert_same_structure(structure[0], other, check_types=check_types)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/nest.py", line 222, in assert_same_structure
    % (len_nest1, nest1, len_nest2, nest2))
ValueError: The two structures don't have the same number of elements.

First structure (14 elements): AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'blstm_seq2seq_attention/tile_batch_1/Reshape:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'blstm_seq2seq_attention/tile_batch_1/Reshape_1:0' shape=(?, 512) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'blstm_seq2seq_attention/tile_batch_1/Reshape_2:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'blstm_seq2seq_attention/tile_batch_1/Reshape_3:0' shape=(?, 512) dtype=float32>)), attention=<tf.Tensor 'blstm_seq2seq_attention/AttentionWrapperZeroState/zeros_1:0' shape=(?, 2048) dtype=float32>, time=<tf.Tensor 'blstm_seq2seq_attention/AttentionWrapperZeroState/zeros:0' shape=() dtype=int32>, alignments=(<tf.Tensor 'blstm_seq2seq_attention/AttentionWrapperZeroState/zeros_2:0' shape=(?, ?) dtype=float32>, <tf.Tensor 'blstm_seq2seq_attention/AttentionWrapperZeroState/zeros_3:0' shape=(?, ?) dtype=float32>, <tf.Tensor 'blstm_seq2seq_attention/AttentionWrapperZeroState/zeros_4:0' shape=(?, ?) dtype=float32>, <tf.Tensor 'blstm_seq2seq_attention/AttentionWrapperZeroState/zeros_5:0' shape=(?, ?) dtype=float32>), alignment_history=(<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f8fa6352f10>, <tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f8fa6309bd0>, <tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f8fa62a94d0>, <tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f8fa62c41d0>))

Second structure (10 elements): AttentionWrapperState(cell_state=(LSTMStateTuple(c=512, h=512), LSTMStateTuple(c=512, h=512)), attention=2048, time=TensorShape([]), alignments=(<tf.Tensor 'blstm_seq2seq_attention/BahdanauAttention/strided_slice_4:0' shape=() dtype=int32>, <tf.Tensor 'blstm_seq2seq_attention/BahdanauAttention/strided_slice_4:0' shape=() dtype=int32>, <tf.Tensor 'blstm_seq2seq_attention/BahdanauAttention/strided_slice_4:0' shape=() dtype=int32>, <tf.Tensor 'blstm_seq2seq_attention/BahdanauAttention/strided_slice_4:0' shape=() dtype=int32>), alignment_history=((), (), (), ()))

**Comment by zh794390558** [comment]
beam_search_decoder can not use alignment_history=True
